# Generated by Django 5.2.3 on 2025-06-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomic_number', models.PositiveIntegerField()),
                ('symbol', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('atomic_weight', models.FloatField()),
                ('group', models.IntegerField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('electron_configuration', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
